version: "3"
services:
  api:
    build: ./api
    networks:
      - backend
      - frontend
    ports:
      - 443:443
      - 8080:8080

  frontend:
    build: ./front
    networks:
      - frontend
    ports:
      - 3000:3000

  mail_api:
    build: ./mail_api
    networks:
      - backend
    ports:
      - 7979:8080

  redis:
    image: redis
    networks:
      - backend
    ports:
      - 6379:6379

  mongodb:
    image: mongo
    container_name: epicRoadTripDb
    networks:
      - backend
    ports:
      - 27017:27017
    volumes:
      - ~/apps/mongo:/data/db
      - ./back/scripts/setupMongo.js:/docker-entrypoint-initdb.d/setupMongo.js:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=epicRoadTrip
      # - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}
      # - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}

  test:
    build: ./test
    networks:
      - backend

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
