openapi: 3.0.0

info:
  version: "1.0.0"
  title: EpicRoadTrip API

paths:
  /ping:
    get:
      summary: Ping the API
      tags:
        - ping
      description: This route is used to check the API liveness.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    default: "pong"

servers:
  - url: http://localhost:9000
    description: Local server
