import axios from 'axios';
import { Helmet } from 'react-helmet';
import { toast } from 'react-toastify';
import styles from 'styles/Home.module.css';
import { Banner, Collection, Header, LargeCard, SmallCard } from '../components';

const Home = () => {
	const citiesGridStyle = {
		'--grid-col-lg': 4,
		'--grid-col-sm': 2,
	} as React.CSSProperties;

	const options = {
		enableHighAccuracy: true,
		timeout: 5000,
		maximumAge: 0,
	};

	const getPosition = (data) => {
		console.log(data);
		axios
			.get(
				`https://api.geoapify.com/v1/geocode/reverse?lat=${data.coords.latitude}&lon=${data.coords.longitude}&apiKey=${process.env.REACT_APP_GEOAPIFY_API_KEY}`
			)
			.then((res) => {
				console.log(res.data);
				console.log(res.data.features[0].properties.city);
			})
			.catch((err) => {
				console.log(err);
			});
	};

	const handlePositionError = (error) => {
		toast.error('Unable to get your location');
	};

	const handlePermission = () => {
		navigator.permissions.query({ name: 'geolocation' }).then(function (result) {
			if (result.state === 'granted') {
				report(result.state);
				navigator.geolocation.getCurrentPosition(getPosition, handlePositionError, options);
			} else if (result.state === 'prompt') {
				report(result.state);
			} else if (result.state === 'denied') {
				report(result.state);
			}
			result.addEventListener('change', function () {
				report(result.state);
			});
		});
	};
	const report = (state) => {
		console.log('Permission ', state);
		toast.warning('Permission ', state);
	};

	return (
		<div className={styles.container}>
			<Helmet>
				<title>Web project</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Helmet>
			<Header />
			<Banner onClick={handlePermission} />
			<Collection title="Explore the cities nearby" style={citiesGridStyle}>
				{Array(8)
					.fill(null)
					.map((_, key) => (
						<SmallCard
							city="Paris"
							description="The city of love"
							distance={10}
							image="https://images.pexels.com/photos/259588/pexels-photo-259588.jpeg?auto=compress&cs=tinysrgb&dpr=3&h=750&w=1260"
							link="/"
							key={key}
						/>
					))}
			</Collection>
			<LargeCard
				image="https://images.pexels.com/photos/259588/pexels-photo-259588.jpeg?auto=compress&cs=tinysrgb&dpr=3&h=750&w=1260"
				title="test"
				btnText="Button"
				link="/"
			/>
		</div>
	);
};

export default Home;
