# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [DELENDA_BRANCH_EST]
  pull_request:
    branches: [DELENDA_BRANCH_EST]
  workflow_dispatch:

jobs:

  secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
      - name: "Create env file"
        run: |  
          touch .env
          cat .env
